bentoml_service_args:
  name: llama3.1
  traffic:
    timeout: 300
  resources:
    gpu: 1
    gpu_type: nvidia-l4
vllm_engine_args:
  model: meta-llama/Meta-Llama-3.1-8B-Instruct
  max_model_len: 2048
  dtype: half
